<?php

declare(strict_types = 1);

namespace PHPCensor\Plugins\CodeQuality;

use PHPCensor\Common\Build\BuildErrorInterface;
use PHPCensor\Common\Build\BuildInterface;
use PHPCensor\Common\Exception\Exception;
use PHPCensor\Common\Plugin\Plugin;

/**
 * Launch Phan.
 *
 * @package    PHP Censor
 * @subpackage Plugins
 *
 * @author Dmitry Khomutov <poisoncorpsee@gmail.com>
 */
class Phan extends Plugin
{
    /**
     * @var string Location on the server where the files are stored. Preferably in the webroot for inclusion
     *             in the readme.md of the repository
     */
    private $location;

    /**
     * @var int
     */
    private $allowedWarnings = 0;

    /**
     * {@inheritdoc}
     */
    public static function getName(): string
    {
        return 'phan';
    }

    /**
     * {@inheritdoc}
     */
    public function execute(): bool
    {
        $executable = $this->commandExecutor->findBinary($this->binaryNames, $this->binaryPath);

        if (!\file_exists($this->location)) {
            \mkdir($this->location, (0777 & ~\umask()), true);
        }

        if (!\is_writable($this->location)) {
            throw new Exception(\sprintf('The location %s is not writable or does not exist.', $this->location));
        }

        // Find PHP files in a file
        $cmd = 'find -L %s -type f -name "**.php"';
        foreach ($this->ignores as $ignore) {
            $cmd .= ' | grep -v '. $ignore;
        }

        $cmd .= ' > %s';

        $this->commandExecutor->executeCommand($cmd, $this->directory, $this->location . '/phan.in');

        // Launch Phan on PHP files with json output
        $cmd = $executable .' -f %s -i -m json -o %s';

        $this->commandExecutor->executeCommand($cmd, $this->location . '/phan.in', $this->location . '/phan.out');

        $warningCount = $this->processReport(\file_get_contents($this->location . '/phan.out'));
        $this->buildMetaWriter->write(
            $this->build->getId(),
            (self::getName() . '-warnings'),
            $warningCount
        );

        $success = true;

        if ($this->allowedWarnings !== -1 && $warningCount > $this->allowedWarnings) {
            $success = false;
        }

        return $success;
    }

    /**
     * {@inheritdoc}
     */
    public static function canExecute(string $stage, BuildInterface $build): bool
    {
        if (BuildInterface::STAGE_TEST === $stage) {
            return true;
        }

        return false;
    }

    /**
     * {@inheritdoc}
     */
    protected function initPluginSettings(): void
    {
        $this->location        = $this->build->getBuildPath() .'phan_tmp';
        $this->allowedWarnings = (int)$this->options->get('allowed_warnings', $this->allowedWarnings);
    }

    /**
     * {@inheritdoc}
     */
    protected function getPluginDefaultBinaryNames(): array
    {
        return [
            'phan',
            'phan.phar',
        ];
    }

    /**
     * Process the Phan Json report.
     *
     * @param string $jsonString
     *
     * @return int
     *
     * @throws Exception
     */
    private function processReport($jsonString)
    {
        $json = \json_decode($jsonString, true);

        if ($json === false || !\is_array($json)) {
            $this->buildLogger->logNormal($jsonString);

            throw new Exception('Could not process the report generated by Phan.');
        }

        $warnings = 0;

        foreach ($json as $data) {
            $this->buildErrorWriter->write(
                $this->build->getId(),
                self::getName(),
                $data['check_name']."\n\n".$data['description'],
                $this->severity((int)$data['severity']),
                isset($data['location']['path']) ? $data['location']['path'] : '??',
                isset($data['location']['lines']['begin']) ? (int)$data['location']['lines']['begin'] : 0,
                isset($data['location']['lines']['end']) ? (int)$data['location']['lines']['end'] : 0
            );

            $warnings++;
        }

        return $warnings;
    }

    /**
     * Transform severity from Phan to PHP-Censor.
     *
     * @param  int $severity
     *
     * @return int
     */
    private function severity(int $severity): int
    {
        if ($severity === 10) {
            return BuildErrorInterface::SEVERITY_CRITICAL;
        }

        if ($severity === 5) {
            return BuildErrorInterface::SEVERITY_NORMAL;
        }

        return BuildErrorInterface::SEVERITY_LOW;
    }
}
